### ISSUE TITLE
Fails without `sshknownhosts` library

### ISSUE THREAD

**Issue by farridav** [weareinteractive/ansible-sftp#1]
Hi, 

When I run my play using your role, i get:

> ERROR: sshknownhosts is not a legal parameter in an Ansible task or handler

After reading through your travis file, I see it relies on `sshknownhosts`? Is there a way this can be listed as a dependency and pulled in as an ansbile role? or you could just use ansibles `lineinfile`, this will do what you need and remove the dependency :)

Thanks for your contribution, and keep up the good work!

**Comment by franklinkim** [comment]
hi, my [ssh role](https://github.com/weareinteractive/ansible-ssh) has a dependency to the [sshknownhost library](https://github.com/bfmartin/ansible-sshknownhosts) which I can't bundle into to role so it's stated in the README file. Just install it and it should be fine!
